FROM golang:1.24 as test

WORKDIR /app

# Install Redis CLI for testing
RUN apt-get update && apt-get install -y redis-tools

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN go mod tidy

# Set environment variables for testing
ENV REDIS=redis://redis-test:6379
ENV UPSTREAM=1.1.1.1:53
ENV DEBUG=1

# Run tests
CMD ["go", "test", "-v", "./..."]