services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 15s
      timeout: 5s
      retries: 5
    command: ["redis-server"]
    ports:
      - 127.0.0.1:6379:6379
  dfirewall:
    depends_on:
      redis:
        condition: service_healthy
    container_name: dfirewall
    restart: "always"
    build: .
    network_mode: host  # Required for DNS interception, also exposes WEB_UI_PORT if enabled
    cap_add:
      - NET_ADMIN
    # Security hardening
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,size=100M,mode=1777
      - /dev/shm:rw,size=100M,mode=1777
    security_opt:
      - no-new-privileges:true
    environment:
      #- "PORT=53"
      - "UPSTREAM=1.1.1.1:53"
      - "REDIS=redis://127.0.0.1:6379"
      #- "ENABLE_EDNS=1" # Enable EDNS Client Subnet (now fixed with IPv4/IPv6 support)
      #- "DEBUG=1"
      - "INVOKE_SCRIPT=/scripts/invoke_linux_ipset.sh"
      #- "EXPIRE_SCRIPT=/scripts/expire_generic.sh" # Enable for non-Linux/non-ipset platforms
      #- "SCRIPT_CONFIG=/config/script-config.json" # Enable per-client script configuration
      #- "BLACKLIST_CONFIG=/config/blacklist-config.json" # Enable IP/domain blacklisting
      #- "WEB_UI_PORT=8080" # Enable web UI for rule management
      - "INVOKE_ALWAYS=1"
    hostname: "dfirewall"
    image: "dfirewall:latest"
    # Use root for NET_ADMIN capability but with security hardening
    user: root
