services:
  redis:
    image: redis:latest
    container_name: redis
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 15s
      timeout: 5s
      retries: 5
    command: ["redis-server"]
    ports:
      - 127.0.0.1:6379:6379
  dfirewall:
    depends_on:
      redis:
        condition: service_healthy
    container_name: dfirewall
    restart: "always"
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      #- "PORT=53"  # DNS port
      #- "WEB_PORT=8080"  # Web UI port (default: 8080)
      - "UPSTREAM=100.64.1.3:53"
      - "REDIS=redis://127.0.0.1:6379"
      - "ENABLE_EDNS=1"
      - "TTL_PAD_SECONDS_DEFAULT=180"
      - "TTL_PAD_SECONDS_192_168_5_120_32=3600"
      - "TTL_PAD_SECONDS_192_168_5_175_32=600"
      - "TTL_PAD_SECONDS_192_168_5_188_32=600"
      #- "DEBUG=1"
      - "INVOKE_SCRIPT=/scripts/invoke_linux_ipset.sh"
      - "INVOKE_ALWAYS=1"
      - "ENABLE_IPV6=1"  # Enable IPv6 support
    hostname: "dfirewall"
    image: "dfirewall:latest"
    user: root
